In [18]:
import pandas as pd
import numpy as np


data_set = pd.read_csv("dataset/data.csv", encoding= "ISO-8859-1", dtype= {"InvoiceNo": str, "CustomerID": str})

data_set.head(5)

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...      17850  United Kingdom
1    536365     71053  ...      17850  United Kingdom
2    536365    84406B  ...      17850  United Kingdom
3    536365    84029G  ...      17850  United Kingdom
4    536365    84029E  ...      17850  United Kingdom

[5 rows x 8 columns]

In [20]:
data_set.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID      object
Country         object
dtype: object

In [21]:
data_set.shape

(541909, 8)

In [19]:
data_set.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Quantity
-80995    16446
-74215    12346
-9600         0
-9360     15838
-9058         0
          ...
 4800     12901
 5568         0
 12540    13256
 74215    12346
 80995    16446
Name: CustomerID, Length: 722, dtype: object

In [25]:
data_set["InvoiceDate"] = pd.to_datetime(data_set["InvoiceDate"])

In [26]:
data_set.head(8)

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...      17850  United Kingdom
1    536365     71053  ...      17850  United Kingdom
2    536365    84406B  ...      17850  United Kingdom
3    536365    84029G  ...      17850  United Kingdom
4    536365    84029E  ...      17850  United Kingdom
5    536365     22752  ...      17850  United Kingdom
6    536365     21730  ...      17850  United Kingdom
7    536366     22633  ...      17850  United Kingdom

[8 rows x 8 columns]

In [41]:
col_info = pd.DataFrame(data_set.dtypes).T.rename(index = {0:"column type"})
col_info = pd.concat([col_info, 
                      pd.DataFrame(data_set.isnull().sum()).T.rename(index= {0:"null values(nb)"})])
col_info = pd.concat([col_info, 
                      pd.DataFrame(data_set.isnull().sum()/data_set.shape[0]*100).T.rename(index = {0:"null values"})])
col_info.head()

                InvoiceNo StockCode Description  ... UnitPrice CustomerID Country
column type        object    object      object  ...   float64     object  object
null values(nb)         0         0        1454  ...         0     135080       0
null values           0.0       0.0    0.268311  ...       0.0  24.926694     0.0

[3 rows x 8 columns]

In [42]:
!pwd

/mnt/datassd/CodeHub/Science/CustomerSegmentation